# -*- coding: utf8 -*-

# Copyright 2019 SIL International (http://scripts.sil.org/)
# Apache License v2.0

class Charset:
    common_name = 'SIL: Meetei Mayek script'
    native_name = 'Meetei Mayek script'
    abbreviation = 'Mtei'
    key = 0xABC0
    glyphs = [
        0xABC0,  # MEETEI MAYEK LETTER KOK
        0xABC1,  # MEETEI MAYEK LETTER SAM
        0xABC2,  # MEETEI MAYEK LETTER LAI
        0xABC3,  # MEETEI MAYEK LETTER MIT
        0xABC4,  # MEETEI MAYEK LETTER PA
        0xABC5,  # MEETEI MAYEK LETTER NA
        0xABC6,  # MEETEI MAYEK LETTER CHIL
        0xABC7,  # MEETEI MAYEK LETTER TIL
        0xABC8,  # MEETEI MAYEK LETTER KHOU
        0xABC9,  # MEETEI MAYEK LETTER NGOU
        0xABCA,  # MEETEI MAYEK LETTER THOU
        0xABCB,  # MEETEI MAYEK LETTER WAI
        0xABCC,  # MEETEI MAYEK LETTER YANG
        0xABCD,  # MEETEI MAYEK LETTER HUK
        0xABCE,  # MEETEI MAYEK LETTER UN
        0xABCF,  # MEETEI MAYEK LETTER I
        0xABD0,  # MEETEI MAYEK LETTER PHAM
        0xABD1,  # MEETEI MAYEK LETTER ATIYA
        0xABD2,  # MEETEI MAYEK LETTER GOK
        0xABD3,  # MEETEI MAYEK LETTER JHAM
        0xABD4,  # MEETEI MAYEK LETTER RAI
        0xABD5,  # MEETEI MAYEK LETTER BA
        0xABD6,  # MEETEI MAYEK LETTER JIL
        0xABD7,  # MEETEI MAYEK LETTER DIL
        0xABD8,  # MEETEI MAYEK LETTER GHOU
        0xABD9,  # MEETEI MAYEK LETTER DHOU
        0xABDA,  # MEETEI MAYEK LETTER BHAM
        0xABDB,  # MEETEI MAYEK LETTER KOK LONSUM
        0xABDC,  # MEETEI MAYEK LETTER LAI LONSUM
        0xABDD,  # MEETEI MAYEK LETTER MIT LONSUM
        0xABDE,  # MEETEI MAYEK LETTER PA LONSUM
        0xABDF,  # MEETEI MAYEK LETTER NA LONSUM
        0xABE0,  # MEETEI MAYEK LETTER TIL LONSUM
        0xABE1,  # MEETEI MAYEK LETTER NGOU LONSUM
        0xABE2,  # MEETEI MAYEK LETTER I LONSUM
        0xABE3,  # MEETEI MAYEK VOWEL SIGN ONAP
        0xABE4,  # MEETEI MAYEK VOWEL SIGN INAP
        0xABE5,  # MEETEI MAYEK VOWEL SIGN ANAP
        0xABE6,  # MEETEI MAYEK VOWEL SIGN YENAP
        0xABE7,  # MEETEI MAYEK VOWEL SIGN SOUNAP
        0xABE8,  # MEETEI MAYEK VOWEL SIGN UNAP
        0xABE9,  # MEETEI MAYEK VOWEL SIGN CHEINAP
        0xABEA,  # MEETEI MAYEK VOWEL SIGN NUNG
        0xABEB,  # MEETEI MAYEK CHEIKHEI
        0xABEC,  # MEETEI MAYEK LUM IYEK
        0xABED,  # MEETEI MAYEK APUN IYEK
        0xABF0,  # MEETEI MAYEK DIGIT ZERO
        0xABF1,  # MEETEI MAYEK DIGIT ONE
        0xABF2,  # MEETEI MAYEK DIGIT TWO
        0xABF3,  # MEETEI MAYEK DIGIT THREE
        0xABF4,  # MEETEI MAYEK DIGIT FOUR
        0xABF5,  # MEETEI MAYEK DIGIT FIVE
        0xABF6,  # MEETEI MAYEK DIGIT SIX
        0xABF7,  # MEETEI MAYEK DIGIT SEVEN
        0xABF8,  # MEETEI MAYEK DIGIT EIGHT
        0xABF9,  # MEETEI MAYEK DIGIT NINE
    ]
