# -*- coding: utf8 -*-

# Copyright 2022 SIL International (http://scripts.sil.org/)
# Apache License v2.0

class Charset:
    common_name = 'SIL: Gunjala Gondi script'
    native_name = 'Gunjala Gondi script'
    abbreviation = 'GunjalaGondi'
    key = 0x11D6C
    glyphs = [
        0x0964,  # DEVANAGARI DANDA
        0x0965,  # DEVANAGARI DOUBLE DANDA
        0x11D60,  # GUNJALA GONDI LETTER A
        0x11D61,  # GUNJALA GONDI LETTER AA
        0x11D62,  # GUNJALA GONDI LETTER I
        0x11D63,  # GUNJALA GONDI LETTER II
        0x11D64,  # GUNJALA GONDI LETTER U
        0x11D65,  # GUNJALA GONDI LETTER UU
        0x11D67,  # GUNJALA GONDI LETTER EE
        0x11D68,  # GUNJALA GONDI LETTER AI
        0x11D6A,  # GUNJALA GONDI LETTER OO
        0x11D6B,  # GUNJALA GONDI LETTER AU
        0x11D6C,  # GUNJALA GONDI LETTER YA
        0x11D6D,  # GUNJALA GONDI LETTER VA
        0x11D6E,  # GUNJALA GONDI LETTER BA
        0x11D6F,  # GUNJALA GONDI LETTER BHA
        0x11D70,  # GUNJALA GONDI LETTER MA
        0x11D71,  # GUNJALA GONDI LETTER KA
        0x11D72,  # GUNJALA GONDI LETTER KHA
        0x11D73,  # GUNJALA GONDI LETTER TA
        0x11D74,  # GUNJALA GONDI LETTER THA
        0x11D75,  # GUNJALA GONDI LETTER LA
        0x11D76,  # GUNJALA GONDI LETTER GA
        0x11D77,  # GUNJALA GONDI LETTER GHA
        0x11D78,  # GUNJALA GONDI LETTER DA
        0x11D79,  # GUNJALA GONDI LETTER DHA
        0x11D7A,  # GUNJALA GONDI LETTER NA
        0x11D7B,  # GUNJALA GONDI LETTER CA
        0x11D7C,  # GUNJALA GONDI LETTER CHA
        0x11D7D,  # GUNJALA GONDI LETTER TTA
        0x11D7E,  # GUNJALA GONDI LETTER TTHA
        0x11D7F,  # GUNJALA GONDI LETTER LLA
        0x11D80,  # GUNJALA GONDI LETTER JA
        0x11D81,  # GUNJALA GONDI LETTER JHA
        0x11D82,  # GUNJALA GONDI LETTER DDA
        0x11D83,  # GUNJALA GONDI LETTER DDHA
        0x11D84,  # GUNJALA GONDI LETTER NGA
        0x11D85,  # GUNJALA GONDI LETTER PA
        0x11D86,  # GUNJALA GONDI LETTER PHA
        0x11D87,  # GUNJALA GONDI LETTER HA
        0x11D88,  # GUNJALA GONDI LETTER RA
        0x11D89,  # GUNJALA GONDI LETTER SA
        0x11D8A,  # GUNJALA GONDI VOWEL SIGN AA
        0x11D8B,  # GUNJALA GONDI VOWEL SIGN I
        0x11D8C,  # GUNJALA GONDI VOWEL SIGN II
        0x11D8D,  # GUNJALA GONDI VOWEL SIGN U
        0x11D8E,  # GUNJALA GONDI VOWEL SIGN UU
        0x11D90,  # GUNJALA GONDI VOWEL SIGN EE
        0x11D91,  # GUNJALA GONDI VOWEL SIGN AI
        0x11D93,  # GUNJALA GONDI VOWEL SIGN OO
        0x11D94,  # GUNJALA GONDI VOWEL SIGN AU
        0x11D95,  # GUNJALA GONDI SIGN ANUSVARA
        0x11D96,  # GUNJALA GONDI SIGN VISARGA
        0x11D97,  # GUNJALA GONDI VIRAMA
        0x11D98,  # GUNJALA GONDI OM
        0x11DA0,  # GUNJALA GONDI DIGIT ZERO
        0x11DA1,  # GUNJALA GONDI DIGIT ONE
        0x11DA2,  # GUNJALA GONDI DIGIT TWO
        0x11DA3,  # GUNJALA GONDI DIGIT THREE
        0x11DA4,  # GUNJALA GONDI DIGIT FOUR
        0x11DA5,  # GUNJALA GONDI DIGIT FIVE
        0x11DA6,  # GUNJALA GONDI DIGIT SIX
        0x11DA7,  # GUNJALA GONDI DIGIT SEVEN
        0x11DA8,  # GUNJALA GONDI DIGIT EIGHT
        0x11DA9,  # GUNJALA GONDI DIGIT NINE
    ]
